* kanagawa-theme
[[https://melpa.org/#/kanagawa-theme][file:https://melpa.org/packages/kanagawa-theme-badge.svg]]
[[https://www.gnu.org/licenses/gpl-3.0][file:https://img.shields.io/badge/License-GPLv3-blue.svg]]

Kanagawa for Emacs is a tuned port of the [[https://github.com/rebelot/kanagawa.nvim][kanagawa]] theme for neovim, originally [[https://github.com/konrad1977][konrad1977]] created the [[https://github.com/konrad1977/kanagawa-emacs][emacs version]] based on the color palette of neovim, subsequently I modified the background color such that consistent with neovim version, abandoned =autothemer= dependency, and improved variable naming style. Images are here: [[https://emacsthemes.com/themes/kanagawa-theme.html][https://emacsthemes.com/themes/kanagawa-theme]]
** Customizations
The theme has some options that can be tweaked via =M-x customize=:
- =kanagawa-theme-comment-italic=
This toggles italics for comments.
- =kanagawa-theme-keyword-italic=
This toggles italics for keywords.
- =kanagawa-theme-underline-parens=
This toggles the underline of matching parens when using show-paren-mode or similar whereas inappearant though.
- =kanagawa-theme-org-bold=
This toggles bold text for org headings.
- =kanagawa-theme-org-height=
This toggles the use of varying org headings heights.
- =kanagawa-theme-org-priority-bold=
This toggles bold text for priority items in agenda view.
- =kanagawa-theme-custom-colors=
This specifies a list of custom colors.
** Acknowledgement
- [[https://github.com/konrad1977/kanagawa-emacs][konrad1977/kanagawa-emacs]]
- [[https://github.com/rebelot/kanagawa.nvim][rebelot/kanagawa.nvim]]
** Copying
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
